spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: test
  freemarker:
    cache: false
    check-template-location: true
    charset: utf-8
    template-loader-path: classpath:/templates
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: wozaizheli
    url: jdbc:mysql://192.168.65.131:3306/img?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  mvc:
    static-path-pattern: /static/**
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.superficial.img.api.*.pojo
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    #capital-mode: true
    #key-generator: com.baomidou.springboot.xxx
    logic-delete-value: 0
    logic-not-delete-value: 1
    meta-object-handler: com.superficial.img.common.config.MybatisObjectHandler
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

  properties:
    mail:
      smtp:
        auth: true
        mailtimeout: 1000
        mailssl: javax.net.ssl.SSLSocketFactory
        starttls:
          enable: true
          required: true
IMG:
  QRCENTER_PATH: static/home/icon.png
server:
  port: 8100
